#!/usr/bin/env bash
# load-moses.sh — boot Moses into every session.
#
# SessionStart hook. Injects a dense block: who owns what, what is deferred and due, what was recently
# VERIFIED, and where the generated infrastructure map is.
#
# WHY (Brad, 2026-08-13): *"from here on out 'you' needs to mean Moses. Each time I start a new
# session … the session should load Moses and everything should go through Moses."* He is nearly
# always building something we built; a session that starts cold re-derives what Moses already knows.
#
# Scope, as agreed: **context and routing, not voice.** This changes what is known and reachable, not
# how the assistant talks. No persona roleplay in working sessions.
#
# The verification ledger is the load-bearing part. It answers the failure a Stop hook structurally
# cannot: on 2026-08-13 the proof that a key worked was in the conversation and got re-derived as
# missing anyway. Facts forty turns back do not get noticed; facts in a dense block at the top do.
#
# Cheap by construction — a few hundred tokens of pointers and recent observations, not a corpus dump.
# Moses's memory is already searchable; this is the index, not the library.
#
# Fails open: any problem prints nothing and the session starts normally.

set -uo pipefail

MEM="$HOME/.claude/memory"
ROSTER=/etc/moses/roster.json

{
  printf 'MOSES SESSION CONTEXT (injected at session start — this is the index, not the library).\n\n'

  # ── Who owns what ─────────────────────────────────────────────────────────
  if [ -r "$ROSTER" ]; then
    printf 'ROSTER — route work to whoever owns the ground:\n'
    python3 -c "
import json
d = json.load(open('$ROSTER'))
for p in d.get('personas', []):
    owns = (p.get('aoe') or {}).get('owns') or []
    first = owns[0] if owns else (p.get('title') or '')
    print(f\"  {p.get('name','?'):10} ({p.get('kind','?'):7}) {first[:78]}\")
" 2>/dev/null || printf '  (roster unreadable)\n'
    printf '\n'
  fi

  # ── Deferred decisions that have come due ─────────────────────────────────
  if command -v moses >/dev/null 2>&1; then
    due=$(moses deferred 2>/dev/null | head -20)
    case "$due" in
      *"nothing deferred"*|"") ;;
      *) printf 'DEFERRED AND DUE:\n%s\n\n' "$due" ;;
    esac
  fi

  # ── Recent verification events ────────────────────────────────────────────
  # The point of the whole hook. Observations with timestamps — NOT standing truths. A line here is
  # a reason to believe and, if it is old, a reason to look again. Never permission to skip looking.
  if [ -r "$MEM/verified.md" ]; then
    printf 'RECENTLY VERIFIED (what was OBSERVED, and when — re-check before relying on an old line):\n'
    grep -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}T' "$MEM/verified.md" 2>/dev/null | tail -20 | sed 's/^/  /'
    printf '\n'
  fi

  # ── Pointers, with freshness ──────────────────────────────────────────────
  if [ -r "$MEM/infrastructure.md" ]; then
    gen=$(grep -m1 -oE 'Written [A-Za-z]+ [0-9-]+ [0-9:]+ [A-Z]+' "$MEM/infrastructure.md" 2>/dev/null)
    printf 'INFRASTRUCTURE: %s/infrastructure.md — GENERATED by moses-inventory (%s).\n' "$MEM" "${gen:-unknown}"
    printf '  Hosts, services, timers, listening ports, and WHICH SCRIPT READS WHICH CONFIG FILE.\n'
    printf '  Check it before asking Brad where a setting lives — that question is answered there.\n\n'
  fi

  # ── DRIFT, AT THE TOP, BEFORE ANY WORK ──────────────────────────────────────
  # Brad, 2026-08-22: "You build something, it gets documented SOMEWHERE that then gets CHECKED by
  # you, Moses, Knight, everybody before any of you does anything."
  #
  # That day a web service on his own domain (moses-dashboard, projects.viatica.travel) turned out to
  # be in no architecture document at all. It had been built days earlier. Nothing caught it because
  # every check validated claims the docs MADE — `arch_check.py` says so in its own output — and a
  # component in no doc is invisible to all of them.
  #
  # So the finding is put where it cannot be missed: at the start of the session, before the first
  # edit. A report nobody reads is the same as no report, and the architecture check had been sitting
  # `failed` in a journal for five days proving exactly that.
  if [ -x "$HOME/Projects/moses/agent/moses-drift" ]; then
    dout=$(XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/1000}" "$HOME/Projects/moses/agent/moses-drift" 2>&1)
    if printf '%s' "$dout" | grep -q '^DRIFT'; then
      printf 'DRIFT — declared vs actually running. FIX OR ACCOUNT FOR THESE BEFORE BUILDING:\n'
      printf '%s\n\n' "$(printf '%s' "$dout" | sed -n '/^DRIFT/,/^$/p' | tail -n +2)"
    else
      printf 'DRIFT: none. Declared matches actual as of session start.\n\n'
    fi
  fi

  printf 'MEMORY INDEX: %s/MEMORY.md. Search the corpus before re-deriving anything.\n' "$MEM"
} > /tmp/.moses-boot.$$ 2>/dev/null

python3 - "/tmp/.moses-boot.$$" <<'PY' 2>/dev/null
import json, sys, os
p = sys.argv[1]
try:
    ctx = open(p).read().strip()
finally:
    try: os.unlink(p)
    except Exception: pass
if ctx:
    print(json.dumps({
        "hookSpecificOutput": {"hookEventName": "SessionStart", "additionalContext": ctx},
        "suppressOutput": True,
    }))
PY
